[package]
name = "pliron-common-dialects"
version = "0.1.0"
edition = "2024"

[dependencies]
pliron = { git = "https://github.com/vaivaswatha/pliron.git" }
pliron-llvm = { git = "https://github.com/vaivaswatha/pliron.git" }
thiserror = "2"
expect-test = "1"
